### ISSUE TITLE
A bug in the get items API the show up inconsitently

### ISSUE THREAD

**Issue by karthikeyan5** [karthikeyan5/dcapp#21]
this error shows up on the server console and the items don't load in the frontend. But on refresh everything back to normal. So far no pattern/repo set is found.

>  ```
> error: Sending 500 ("Server Error") response:
>  Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual t
> hat corresponds to your MySQL server version for the right syntax to use near '?
>  ) as sizerange WHERE sizerange.idsizetype = sizetype.id' at line 1
>     at Query.Sequence._packetToError (C:\Users\kartxxxxxxxxxxx\Documents\git\dca
> pp\node_modules\sails-mysql\node_modules\mysql\lib\protocol\sequences\Sequence.j
> s:48:14)
>     at Query.ErrorPacket (C:\Users\kartxxxxxxxxxxx\Documents\git\dcapp\node_modu
> les\sails-mysql\node_modules\mysql\lib\protocol\sequences\Query.js:83:18)
>     at Protocol._parsePacket (C:\Users\kartxxxxxxxxxxx\Documents\git\dcapp\node_
> modules\sails-mysql\node_modules\mysql\lib\protocol\Protocol.js:280:23)
>     at Parser.write (C:\Users\kartxxxxxxxxxxx\Documents\git\dcapp\node_modules\s
> ails-mysql\node_modules\mysql\lib\protocol\Parser.js:73:12)
>     at Protocol.write (C:\Users\kartxxxxxxxxxxx\Documents\git\dcapp\node_modules
> \sails-mysql\node_modules\mysql\lib\protocol\Protocol.js:39:16)
>     at Socket.<anonymous> (C:\Users\kartxxxxxxxxxxx\Documents\git\dcapp\node_mod
> ules\sails-mysql\node_modules\mysql\lib\Connection.js:96:28)
>     at emitOne (events.js:116:13)
>     at Socket.emit (events.js:211:7)
>     at addChunk (_stream_readable.js:263:12)
>     at readableAddChunk (_stream_readable.js:250:11)
>     at Socket.Readable.push (_stream_readable.js:208:10)
>     at TCP.onread (net.js:607:20)
>     --------------------
>     at Protocol._enqueue (C:\Users\kartxxxxxxxxxxx\Documents\git\dcapp\node_modu
> les\sails-mysql\node_modules\mysql\lib\protocol\Protocol.js:141:48)
>     at PoolConnection.query (C:\Users\kartxxxxxxxxxxx\Documents\git\dcapp\node_m
> odules\sails-mysql\node_modules\mysql\lib\Connection.js:201:25)
>     at __QUERY__ (C:\Users\kartxxxxxxxxxxx\Documents\git\dcapp\node_modules\sail
> s-mysql\lib\adapter.js:107:22)
>     at afterwards (C:\Users\kartxxxxxxxxxxx\Documents\git\dcapp\node_modules\sai
> ls-mysql\lib\connections\spawn.js:84:5)
>     at C:\Users\kartxxxxxxxxxxx\Documents\git\dcapp\node_modules\sails-mysql\lib
> \connections\spawn.js:40:7
>     at Ping.onOperationComplete [as _callback] (C:\Users\kartxxxxxxxxxxx\Documen
> ts\git\dcapp\node_modules\sails-mysql\node_modules\mysql\lib\Pool.js:99:5)
>     at Ping.Sequence.end (C:\Users\kartxxxxxxxxxxx\Documents\git\dcapp\node_modu
> les\sails-mysql\node_modules\mysql\lib\protocol\sequences\Sequence.js:96:24)
>     at Ping.Sequence.OkPacket (C:\Users\kartxxxxxxxxxxx\Documents\git\dcapp\node
> _modules\sails-mysql\node_modules\mysql\lib\protocol\sequences\Sequence.js:105:8
> )
>     at Protocol._parsePacket (C:\Users\kartxxxxxxxxxxx\Documents\git\dcapp\node_
> modules\sails-mysql\node_modules\mysql\lib\protocol\Protocol.js:280:23)
>     at Parser.write (C:\Users\kartxxxxxxxxxxx\Documents\git\dcapp\node_modules\s
> ails-mysql\node_modules\mysql\lib\protocol\Parser.js:73:12)
>     at Protocol.write (C:\Users\kartxxxxxxxxxxx\Documents\git\dcapp\node_modules
> \sails-mysql\node_modules\mysql\lib\protocol\Protocol.js:39:16)
>     at Socket.<anonymous> (C:\Users\kartxxxxxxxxxxx\Documents\git\dcapp\node_mod
> ules\sails-mysql\node_modules\mysql\lib\Connection.js:96:28)
>     at emitOne (events.js:116:13)
>     at Socket.emit (events.js:211:7)
>     at addChunk (_stream_readable.js:263:12)
>     at readableAddChunk (_stream_readable.js:250:11)
>     at Socket.Readable.push (_stream_readable.js:208:10)
>     at TCP.onread (net.js:607:20)
> ```

**Comment by karthikeyan5** [comment]
this bug has been fixed in the above commit.... it has not shown up since the above was deployed... hence, closing this issue...
