### ISSUE TITLE
server crash during update supplier

### ISSUE THREAD

**Issue by karthikeyan5** [karthikeyan5/dcapp#23]
server crashes with the following trace

> `2018-09-04 16:24:07.605 +05:30: ReferenceError: q1 is not defined
    at C:\Users\karXXXXXXXXXXXX\Documents\git\dcapp\api\controllers\DcController.js:202:38
    at C:\Users\karXXXXXXXXXXXX\Documents\git\dcapp\node_modules\sails-mysql\lib\connections\spawn.js:120:16
    at Object.poolfully [as releaseConnection] (C:\Users\karXXXXXXXXXXXX\Documents\git\dcapp\node_modules\sails-mysql\lib\connections\release.js:28:12)
    at Query._callback (C:\Users\karXXXXXXXXXXXX\Documents\git\dcapp\node_modules\sails-mysql\lib\connections\spawn.js:105:35)
    at Query.Sequence.end (C:\Users\karXXXXXXXXXXXX\Documents\git\dcapp\node_modules\sails-mysql\node_modules\mysql\lib\protocol\sequences\Sequence.js:96:24)
    at Query._handleFinalResultPacket (C:\Users\karXXXXXXXXXXXX\Documents\git\dcapp\node_modules\sails-mysql\node_modules\mysql\lib\protocol\sequences\Query.js:144:8)
    at Query.EofPacket (C:\Users\karXXXXXXXXXXXX\Documents\git\dcapp\node_modules\sails-mysql\node_modules\mysql\lib\protocol\sequences\Query.js:128:8)
    at Protocol._parsePacket (C:\Users\karXXXXXXXXXXXX\Documents\git\dcapp\node_modules\sails-mysql\node_modules\mysql\lib\protocol\Protocol.js:280:23)
    at Parser.write (C:\Users\karXXXXXXXXXXXX\Documents\git\dcapp\node_modules\sails-mysql\node_modules\mysql\lib\protocol\Parser.js:73:12)
    at Protocol.write (C:\Users\karXXXXXXXXXXXX\Documents\git\dcapp\node_modules\sails-mysql\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (C:\Users\karXXXXXXXXXXXX\Documents\git\dcapp\node_modules\sails-mysql\node_modules\mysql\lib\Connection.js:96:28)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:607:20)`

**Comment by karthikeyan5** [comment]
c41d8c596aa258ccfc368411bfbe818370755a46 fixes this.
